# Generated by Django 4.2.5 on 2023-10-09 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('specialty', models.CharField(max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_linked', models.DateField(auto_now_add=True)),
                ('date_unlinked', models.DateField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medic.medic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medic',
            name='patients',
            field=models.ManyToManyField(through='medic.Membership', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='medic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
