# Generated by Django 4.2.5 on 2023-10-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0002_alter_medic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medic',
            name='id',
        ),
        migrations.AddField(
            model_name='medic',
            name='ruc',
            field=models.IntegerField(default=1234, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
