# Generated by Django 4.2.5 on 2023-10-09 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medic', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('dose', models.PositiveSmallIntegerField(choices=[(0, 'Mg'), (1, 'Ml'), (2, 'Pill'), (3, 'Drop'), (4, 'Shot')], null=True)),
                ('every', models.PositiveSmallIntegerField(default=1)),
                ('frequency', models.PositiveSmallIntegerField(choices=[(0, 'Hourly'), (1, 'Daily'), (7, 'Weekly'), (14, 'Biweekly'), (30, 'Monthly'), (365, 'Once')], null=True)),
                ('notes', models.TextField(max_length=512)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('prescribed_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medic.medic')),
            ],
        ),
    ]
