# Generated by Django 4.2.5 on 2023-10-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_id', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('blood_type', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'O Positive'), (2, 'O Negative'), (3, 'A Positive'), (4, 'A Negative'), (5, 'B Positive'), (6, 'B Negative'), (7, 'Ab Positive'), (8, 'Ab Negative')], default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
